"""Init

Revision ID: 17524c949c62
Revises:
Create Date: 2025-11-21 19:55:45.250698

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17524c949c62"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("includes", postgresql.ARRAY(sa.String), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variable",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            server_default=sa.text("uuid_generate_v4()"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("variable")
    op.drop_table("project")
    # ### end Alembic commands ###
