"""Обновил Variable

Revision ID: 3e1ac67ee2e0
Revises: e7aec5deda76
Create Date: 2025-11-23 08:11:55.111106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e1ac67ee2e0"
down_revision: Union[str, Sequence[str], None] = "e7aec5deda76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "variable",
        sa.Column(
            "is_secret",
            sa.Boolean(),
            nullable=False,
            server_default="f",
        ),
    )
    op.alter_column("variable", "value", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("variable", "value", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("variable", "is_secret")
    # ### end Alembic commands ###
