"""Добавил ProjectGroup

Revision ID: e7aec5deda76
Revises: 17524c949c62
Create Date: 2025-11-22 15:40:27.287264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7aec5deda76"
down_revision: Union[str, Sequence[str], None] = "17524c949c62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_group",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("project", sa.Column("group_id", sa.Uuid(), nullable=True))
    op.alter_column(
        "project",
        "includes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.create_foreign_key(None, "project", "project_group", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project", type_="foreignkey")
    op.alter_column(
        "project",
        "includes",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.drop_column("project", "group_id")
    op.drop_table("project_group")
    # ### end Alembic commands ###
